version: "3.9"
services:
  backend:
    image: matiasvazquezmacri/backend-java-grupo6:V8
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - integrador
  db:
    container_name: mysql_container
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: 1023c01_GRUPO6
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: 1023c01_GRUPO6
      MYSQL_PASSWORD: Vo7tahh4
    networks:
      - integrador
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    restart: always
networks:
  integrador:
    driver: bridge
volumes:
  db: